name: Linters

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Commit messages
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 200

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install commitlint
        run: npm install --no-save @commitlint/cli @commitlint/config-conventional

      - name: Lint commit messages
        run: >
          npx commitlint --verbose
          --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }}

  linter:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Fetch frappe semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Install semgrep
        run: pip install semgrep

      - name: Run semgrep
        run: semgrep ci --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness
